# Polars-based parsing data existing in ressources folder

In [111]:
import polars as pl

In [112]:
df_stops = pl.read_csv("../ressources/stops.txt")
df_stops.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Nation    ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 875       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Chatou -  ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Croissy   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 83        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Le        ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Vésinet - ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆ Centre    ┆           ┆   ┆          ┆           ┆           ┆           │
│ 84        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Denfert-R ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ochereau  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 890       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Cité Univ ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ersitaire ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 843       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

# routes.txt description
- route_type :
    - 0 : tram
    - 1 : metro
    - 2 : RER TER
    - 3 : bus

In [113]:
df_routes = pl.read_csv("../ressources/routes.txt")
df_routes.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ route_id  ┆ agency_id ┆ route_sho ┆ route_lon ┆ … ┆ route_url ┆ route_col ┆ route_tex ┆ route_so │
│ ---       ┆ ---       ┆ rt_name   ┆ g_name    ┆   ┆ ---       ┆ or        ┆ t_color   ┆ rt_order │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:C016 ┆ IDFM:1080 ┆ 4244      ┆ 4244      ┆ … ┆ null      ┆ 82DC73    ┆ 000000    ┆ null     │
│ 24        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C023 ┆ IDFM:1081 ┆ 5310      ┆ 5310      ┆ … ┆ null      ┆ 82C8E6    ┆ 000000    ┆ null     │
│ 13        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C000 ┆ IDFM:1087 ┆ 761       ┆ 761       ┆ … ┆ null      ┆ FFBE00    ┆ 000000    ┆ null     │
│ 29        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C006 ┆ IDFM:64   ┆ 2234      ┆ 2234      ┆ … ┆ null      ┆ 640082    ┆ FFFFFF    ┆ null     │
│ 32        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C001 ┆ IDFM:1081 ┆ 5233      ┆ 5233      ┆ … ┆ null      ┆ DC9600    ┆ 000000    ┆ null     │
│ 64        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [114]:
df_routes.filter(pl.col("route_type").is_in([1,2])).select(["route_id", "route_long_name", "route_type"]).sort("route_id")

shape: (40, 3)
┌─────────────┬───────────────────────────┬────────────┐
│ route_id    ┆ route_long_name           ┆ route_type │
│ ---         ┆ ---                       ┆ ---        │
│ str         ┆ str                       ┆ i64        │
╞═════════════╪═══════════════════════════╪════════════╡
│ IDFM:C01371 ┆ 1                         ┆ 1          │
│ IDFM:C01372 ┆ 2                         ┆ 1          │
│ IDFM:C01373 ┆ 3                         ┆ 1          │
│ IDFM:C01374 ┆ 4                         ┆ 1          │
│ IDFM:C01375 ┆ 5                         ┆ 1          │
│ …           ┆ …                         ┆ …          │
│ IDFM:C01863 ┆ TER Hauts-de-France       ┆ 2          │
│ IDFM:C02368 ┆ TER Centre - Val de Loire ┆ 2          │
│ IDFM:C02370 ┆ TER Normandie             ┆ 2          │
│ IDFM:C02375 ┆ TER Normandie             ┆ 2          │
│ IDFM:C02711 ┆ V                         ┆ 2          │
└─────────────┴───────────────────────────┴────────────┘

In [115]:
df_trips = pl.read_csv("../ressources/trips.txt")
df_trips.head()

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ route_id  ┆ service_i ┆ trip_id   ┆ trip_head ┆ … ┆ block_id ┆ shape_id  ┆ wheelchai ┆ bikes_all │
│ ---       ┆ d         ┆ ---       ┆ sign      ┆   ┆ ---      ┆ ---       ┆ r_accessi ┆ owed      │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str      ┆ str       ┆ ble       ┆ ---       │
│           ┆ str       ┆           ┆ str       ┆   ┆          ┆           ┆ ---       ┆ i64       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:C013 ┆ IDFM:1    ┆ IDFM:RATP ┆ Funiculai ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 85        ┆           ┆ :COU_RATP ┆ re Gare   ┆   ┆          ┆ 7_2       ┆           ┆           │
│           ┆           ┆ _388795_3 ┆ basse     ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 139…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:1    ┆ IDFM:RATP ┆ Porte de  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 74        ┆           ┆ :COU_RATP ┆ l'Essonne ┆   ┆          ┆ 0_274     ┆           ┆           │
│           ┆           ┆ _017DIM01 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Dim…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C005 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 0         ┆ 0         │
│ 62        ┆           ┆ :local-17 ┆ 2 F       ┆   ┆          ┆ 3_8659    ┆           ┆           │
│           ┆           ┆ 5995-C005 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 62-…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 92        ┆           ┆ :local-17 ┆ 2 F       ┆   ┆          ┆ 3_8663    ┆           ┆           │
│           ┆           ┆ 5995-C017 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 92-…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C005 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 63        ┆           ┆ :local-17 ┆ 2 Gare    ┆   ┆          ┆ 0_256     ┆           ┆           │
│           ┆           ┆ 5995-C005 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 63-…      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [116]:
# exemple of a specific line (exemple RER A)
df_trips.join(df_routes, on="route_id", how="inner").filter(pl.col("route_type").eq(2), pl.col("route_long_name").eq("A"))

shape: (5_548, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ route_id  ┆ service_i ┆ trip_id   ┆ trip_head ┆ … ┆ route_url ┆ route_col ┆ route_tex ┆ route_so │
│ ---       ┆ d         ┆ ---       ┆ sign      ┆   ┆ ---       ┆ or        ┆ t_color   ┆ rt_order │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ NANI      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 7973483   ┆ NCF:dee0d ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 87e-8a58- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4a0…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ NANI      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 7973483   ┆ NCF:5a1b6 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 0c5-ad0a- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 41b…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ NANI      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 7973483   ┆ NCF:f48dc ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 593-b25b- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4b6…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ NANI      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 7973483   ┆ NCF:7a18c ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ a8f-c7fd- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 45e…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ NANI      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 7973483   ┆ NCF:85d7d ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 9e9-5e39- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 490…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ YCAR      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 8183302   ┆ NCF:032a2 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7f2-07dd- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4e4…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ BENJ      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 8183302   ┆ NCF:ac415 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 515-89b8- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 475…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ UPIR      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 8183433   ┆ NCF:04989 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ed2-c09d- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4fc…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ QURE      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 8183433   ┆ NCF:4bd60 ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 142-2a84- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4a7…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ OPUS      ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆ 8183433   ┆ NCF:0f26f ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 1db-20ba- ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 42c…      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [117]:
df_transfers = pl.read_csv("../ressources/transfers.txt")
df_transfers.head()

shape: (5, 4)
┌──────────────┬─────────────┬───────────────┬───────────────────┐
│ from_stop_id ┆ to_stop_id  ┆ transfer_type ┆ min_transfer_time │
│ ---          ┆ ---         ┆ ---           ┆ ---               │
│ str          ┆ str         ┆ i64           ┆ i64               │
╞══════════════╪═════════════╪═══════════════╪═══════════════════╡
│ IDFM:492619  ┆ IDFM:492621 ┆ 2             ┆ 240               │
│ IDFM:463079  ┆ IDFM:21966  ┆ 2             ┆ 132               │
│ IDFM:495206  ┆ IDFM:489165 ┆ 2             ┆ 424               │
│ IDFM:18212   ┆ IDFM:24386  ┆ 2             ┆ 255               │
│ IDFM:16909   ┆ IDFM:21291  ┆ 2             ┆ 240               │
└──────────────┴─────────────┴───────────────┴───────────────────┘

In [118]:
# exemple of transfers between stations chatelet
stop_id_chatelet = df_stops.filter(pl.col("stop_name").eq("Châtelet - Les Halles")).select("stop_id").to_series()[0]
df_transfers.filter(pl.col("from_stop_id").eq(stop_id_chatelet)).join(df_stops, left_on="to_stop_id", right_on="stop_id", how="inner").select(["transfer_type", "stop_name"]).unique()

shape: (4, 2)
┌───────────────┬─────────────────────────────────┐
│ transfer_type ┆ stop_name                       │
│ ---           ┆ ---                             │
│ i64           ┆ str                             │
╞═══════════════╪═════════════════════════════════╡
│ 2             ┆ Châtelet                        │
│ 2             ┆ Rivoli - Pont Neuf              │
│ 2             ┆ Les Halles                      │
│ 2             ┆ Les Halles - Centre Georges Po… │
└───────────────┴─────────────────────────────────┘